stages: 
  - build_files
  - add_orthos
  
build_gaf:
  stage: build_files
  script:
    - cd ~/
    - pwd
    - bash setup.sh $CI_PROJECT_PATH $CI_COMMIT_REF_NAME
    - cd $CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
    - pwd
    - git reset --hard origin/master
    - git pull
    - bash scripts/xenbase_gaf_driver.sh $CI_COMMIT_SHA
    - sudo -S cp output-files/*enbase.EBI* /data/ftp/pub/DataExchange/GO/
    - sudo -S cp output-files/*annotation* /data/ftp/pub/DataExchange/GO/
    - git add --all output-files/.
    - git commit -m "[skip ci] automated upload from pipeline"
    - git push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"' 
      when: always    # Only run on scheduled or manual triggers
    - when: never     # Skip on all other triggers (including pushes)

add_ortholog_annotations:
  stage: add_orthos
  script:
    - bash scripts/add_orthologs_driver.sh
  rules:              # Should only trigger this stage once the xenbase.gaf (assumed noctua output file) is added/modified on repo
    - changes:
      - output-files/xenbase.gaf    # CHECK!!: may need to change this to noctua output filename if different
